### ISSUE TITLE
unable to import pyqt4 submodules in macosx

### ISSUE THREAD

**Issue by amrit-poudel** [Werkov/PyQt4#1]
I get the following error when I try to import pyqt4 submodule in macosx 10.10:

$  python -c "from PyQt4 import QtCore"

ImportError: dlopen(/Users/Desktop/lib/python2.7/site-packages/PyQt4/QtCore.so, 2): Library not loaded: @rpath/QtCore.framework/Versions/5/QtCore

  Referenced from: /Users/Desktop/lib/python2.7/site-packages/PyQt4/QtCore.so
  Reason: image not found

I installed pyqt4 from: 

https://riverbankcomputing.com/software/pyqt/download

PyQt-mac-gpl-4.11.4.tar.gz	MacOS/X source

cd PyQt-mac-gpl-4.11.4
python configure-ng.py --destdir=/Users/Desktop/lib/python2.7/site-packages --sip-incdir=/Users/Desktop/include
make 
make install

I have a 64 bit python 2.7.9 and I installed qt using online installer. I did not compile it from the source since that takes a huge amount of memory.

I installed qt using:

qt-unified-mac-x64-2.0.2-2-online.dmg

which is a 64 bit qt.

I noticed that every .so files created by pyqt4  refers to some dylib which does not exist anymore. 
For instance, QtGui.so refers to libQtGui.dylib,
QtWidgets.so refers to libQtWidgets.dylib, and so forth. Every PyQt4
Qt*.so should have a matching libQt*.dylib, it appears.

Do you have any idea how I can fix this?

**Comment by Werkov** [comment]
Hi, QED.
I'm not sure this repository is the right place to ask. I can only say that it seems to be some issue specific to Mac OS X environment which I have unfortunately no experience with. I'd suggest forwarding your question to StackOverflow.

HTH, Michal

**Comment by amrit-poudel** [comment]
Ok. thanks!
